import { defineConfig, moduleFederationPlugin } from 'vite'
import { withZephyr } from 'zephyr-rolldown-plugin';

export default defineConfig({
    define: {
        // The webpack remote button is using development NODE_ENV, make sure the host react-dom also using it.
        'process.env.NODE_ENV': JSON.stringify('development'),
    },
    preview: {
        port: 5175,
    },
    build: {
        minify: false,
        rollupOptions: {
            plugins: [
                moduleFederationPlugin({
                    name: 'host',
                    remotes: {
                        'rolldown-vite': 'http://localhost:5176/mf-manifest.json',
                        // generated by https://github.com/rolldown/rolldown-mf-webpack-remote
                        webpack: 'webpack@https://unpkg.com/rolldown-mf-webpack-remote@1.0.0/dist/remoteEntry.js',
                    },
                    shared: {
                        react: {
                            singleton: true,
                        },
                    },
                }),
                withZephyr(),
            ]
        },
    }
})
